name: CI-CD-Pilpeline-to-AWS-EB
env:
    EB_PACKAGE_S3_BUCKET_NAME : "alex-app-packages"
    EB_APPLICATION_NAME       : "myapp"
    EB_ENVIRONMENT_NAME       : "Myapp-env"
    DEPLOY_PACKAGE_NAME       : "myapp_${{ github.sha }}.zip"
    AWS_REGION_NAME           : "us-east-1"

on          :
  push      :
    branches:
             - master

jobs:
 my-ci-part:
    runs-on: ubuntu-latest
    
    steps:
      - name: Git clone our repo
        uses: actions/checkout@v1
     
      - name: Create ZIP deployment package 
        run : zip -r ${{ env.DEPLOY_PACKGAGE_NAME }} ./ -x *.git*
        
      - name: Configure my AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
           aws-access-key-id    :  ${{ secrets.MY_AWS_ACCESS_KEY }}
           aws-secret-access-key:  ${{ secrets.MY_AWS_SECRET_KEY }}
           aws-region           :  ${{ env.AWS_REGION_NAME }}
           
      - name: Copy deployment package to S3 bucket
        run : aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }}  s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/
        
      - name : Print finish title
        run: echo "CI completed (test)"
     
